# Compile the security headers in a file to avoid duplicating the directives
# in the main configuration file. The "add_header" directives have the
# "always" instruction so that the headers are added on every response,
# regardless of whether it was a successful response or not.
#
# Add a header that prevents MIME type sniffing.
add_header X-Content-Type-Options "nosniff" always;

# Add a header that disallows framing the user interface.
add_header X-Frame-Options "DENY" always;

# Add a header that controls how much referrer information is included
# with the requests. The full URL is sent for the same origin, and
# the origin for cross-origin requests.
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# Add a header specifying the restrictions for where the Javascript,
# image, font and styling files can be loaded from. It also restricts where
# the UI will be able to send requests to, and where it can load frames
# from. A fallback "default-src" for any non-specified content just allows
# loading that content from the same origin.
#
# The "unsafe-inline" directive allows inline scripts and event handlers
# required by third-party tracking (Adobe Analytics / dpal.js) and
# TrustArc's cookie consent banner. We attempted individually whitelsiting
# those scripts and hashes, but it's very complicated to do and to keep
# updated.
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' static.redhat.com www.redhat.com assets.adobedtm.com www.google.com www.gstatic.com cdn.segment.com consent.trustarc.com; connect-src 'self' registration-service-toolchain-host-operator.apps.rstage.wybr.p1.openshiftapps.com api-toolchain-host-operator.apps.rstage.wybr.p1.openshiftapps.com registration-service-toolchain-host-operator.apps.sandbox.x8i5.p1.openshiftapps.com api-toolchain-host-operator.apps.sandbox.x8i5.p1.openshiftapps.com sso.redhat.com sandbox.redhat.com smetrics.redhat.com id.redhat.com cdn.segment.com api.segment.io hooks.workato.com consent.trustarc.com; img-src 'self' data: static.redhat.com www.gstatic.com consent.trustarc.com; style-src 'self' 'unsafe-inline' www.gstatic.com; font-src 'self' fonts.gstatic.com consent.trustarc.com; frame-src www.google.com www.youtube.com consent.trustarc.com consent-pref.trustarc.com;" always;
